from typing import List



def split_by_separator(string: str, separator: str, maxsplit: int = -1) -> List[str]:

    """Splits a string into substrings based on a separator string.



    Args:

        string: The input string to be split.

        separator: The separator string used to split the input string.

        maxsplit: The maximum number of splits to perform. If not provided,

            the string is split into all possible substrings.



    Returns:

        A list of substrings generated by splitting the input string based on

        the separator string.

    """

    substrings = string.split(separator, maxsplit)

    return substrings

