import time



def generate_token() -> str:

    """Generates a token consisting of two timestamps separated by a space.

    The first timestamp represents the time the token was generated, and the second timestamp represents the time the token will expire.

    """

    return f"{time.time()}:{time.time() + 30}"



def is_expired(token: str) -> bool:

    """Checks if a token has expired.

    Args:

        token: A token generated by the `generate_token()` function.

    Returns:

        True if the token has expired, False otherwise.

    """

    current_time = time.time()

    first_timestamp, second_timestamp = token.split(':')

    first_timestamp = float(first_timestamp)

    second_timestamp = float(second_timestamp)

    return current_time - first_timestamp > 30

