from typing import IO



def read_source(file: str) -> str:

    """Reads the content of a file and returns it as a string, skipping any lines that start with `#`.

    A comment is added at the beginning of the returned value stating that it has been generated by this function.

    Args:

        file: The path to the file to be read.

    """

    with open(file, 'r') as f:

        lines = f.readlines()

    result = ''

    for line in lines:

        if not line.startswith('#'):

            result += line

    result = '# This file has been generated by your function\n' + result

    return result

